### PR TITLE
Idiomatic dating

### PR DESCRIPTION
**Pull request by matthewjay15**
Hi Danny

Added some code to make outputting the date idiomatic. I'm not sure if it's right but I'm sure you'll get the idea. You need to incorporate something for Prid. Kal. (i.e. the last day of the month - annoying to code because of leap years).

### CODE REVIEW

**Comment by tech189** [comment]
Thanks! I'll merge it and then make the changes on the master branch

**Comment by tech189** [comment]
Made my changes in commit a719f4e, see what you think!
I'll need to work out some way to automate tests...

**Comment by matthewjay15** [comment]
Looks good as far as I can tell! There’s only one addition to be worked out. The Roman’s actually said something like “a.d. bis XVI Kal Mar” for the leap year. But I need to figure out exactly what it is they said (what I’ve written here is wrong).

Matthew A Jay
PhD Student in Legal Epidemiology
UCL Legal Epidemiology Group<https://www.ucl.ac.uk/child-health/research/population-policy-and-practice/child-health-informatics-group/legal-epidemiology-group>
Child Health Informatics Group<https://www.ucl.ac.uk/child-health/research/population-policy-and-practice/child-health-informatics-group>

Co-ordinator and spoken Latin tutor
UCL Latinitas Society<http://www.soclatlon.wordpress.com/>

Episode 6 of «Salvi Sitis!» - the Latin language epidemiology podcast – is out now! www.salvisitis.libsyn.com<http://www.salvisitis.libsyn.com/> / @SalviSitisPod<http://www.twitter.com/SalviSitisPod>

UCL Great Ormond Street Institute of Child Health
30 Guilford Street, London WC1N 1EH
Email: matthew.jay.15@ucl.ac.uk<mailto:matthew.jay.15@ucl.ac.uk>
Twitter: @mattjayresearch<https://twitter.com/mattjayresearch>
Personal URL: https://matthewjayresearch.wordpress.com/

[cid:image001.png@01D4A8CA.3FB7B050]

**Comment by tech189** [comment]
Sorry I realise in my previous comment I posted the wrong commit - my changes are in a719f4e (not 7b895a6) but you've probably seen them in the master branch!

According to this page: http://www.novaroma.org/nr/Roman_dates they used a.d. bis VI Kal. to distinguish between the 24th of February on a leap year and on a normal year. Does that seem right?

**Comment by matthewjay15** [comment]
Ah yes, that’s it!

Matthew A Jay
PhD Student in Legal Epidemiology
UCL Legal Epidemiology Group<https://www.ucl.ac.uk/child-health/research/population-policy-and-practice/child-health-informatics-group/legal-epidemiology-group>
Child Health Informatics Group<https://www.ucl.ac.uk/child-health/research/population-policy-and-practice/child-health-informatics-group>

Co-ordinator and spoken Latin tutor
UCL Latinitas Society<http://www.soclatlon.wordpress.com/>

Episode 6 of «Salvi Sitis!» - the Latin language epidemiology podcast – is out now! www.salvisitis.libsyn.com<http://www.salvisitis.libsyn.com/> / @SalviSitisPod<http://www.twitter.com/SalviSitisPod>

UCL Great Ormond Street Institute of Child Health
30 Guilford Street, London WC1N 1EH
Email: matthew.jay.15@ucl.ac.uk<mailto:matthew.jay.15@ucl.ac.uk>
Twitter: @mattjayresearch<https://twitter.com/mattjayresearch>
Personal URL: https://matthewjayresearch.wordpress.com/

[cid:image001.png@01D4A8CA.3FB7B050]

**Pull request merged**
